// Ghidra headless post-script: decompile every function in the current
// program and write the C source to a single .c file under decomp/.
// Output filename comes from the script arg (passed via -postScript).
//@category Decompilation

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;

public class DumpDecompiled extends GhidraScript {
    @Override
    protected void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length < 1) {
            println("usage: DumpDecompiled <output.c>");
            return;
        }
        File outFile = new File(args[0]);
        outFile.getParentFile().mkdirs();
        DecompInterface decomp = new DecompInterface();
        decomp.toggleCCode(true);
        decomp.toggleSyntaxTree(false);
        if (!decomp.openProgram(currentProgram)) {
            println("ERROR: openProgram failed: " + decomp.getLastMessage());
            return;
        }
        int total = 0, ok = 0, fail = 0;
        try (PrintWriter w = new PrintWriter(new BufferedWriter(new FileWriter(outFile)))) {
            w.println("// Decompiled output for " + currentProgram.getName());
            w.println("// Generated by Ghidra " + getState().getTool());
            w.println();
            FunctionIterator it = currentProgram.getFunctionManager().getFunctions(true);
            while (it.hasNext()) {
                if (monitor.isCancelled()) break;
                Function f = it.next();
                total++;
                if (f.isThunk() || f.isExternal()) continue;
                DecompileResults res = decomp.decompileFunction(f, 60, monitor);
                if (res != null && res.decompileCompleted() && res.getDecompiledFunction() != null) {
                    w.println("// ===== " + f.getName() + " @ " + f.getEntryPoint() + " =====");
                    w.println("// signature: " + f.getPrototypeString(true, true));
                    w.println(res.getDecompiledFunction().getC());
                    w.println();
                    ok++;
                } else {
                    String msg = (res == null) ? "(null)" : res.getErrorMessage();
                    w.println("// ===== " + f.getName() + " @ " + f.getEntryPoint() +
                              "  (FAILED: " + msg + ") =====");
                    fail++;
                }
                if (total % 100 == 0) println("  ... " + total + " functions processed");
            }
        }
        println("done: " + ok + " ok, " + fail + " failed (out of " + total + " total)");
    }
}
